server:
  port: 8090
  servlet:
    context-path: /rzk-videos


logging:
  config:
    classpath: logback-spring.xml


spring:
  profiles:
    active: dev
  datasource:
    name: oos
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.221.132.14:/lnsfwx-videos-dev?characterEncoding=utf8&useSSL=false
    username: root
    password: rzkruizhukai123.
    type: com.alibaba.druid.pool.DruidDataSource
    #Druid 配置
    filters: stat
    initial-size: 2 #连接池初始化时初始化的数据库连接数
    max-idle: 10 #最大等待连接中的数量
    min-idle: 1 #最小等待连接中的数量
    max-active: 20 #最大连接数
    #最大等待毫秒数, 单位为 ms, 超过时间会出错误信息
    max-wait: 60000
    # 指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
    time-between-eviction-runs-millis: 60000
    # 指定一个空闲连接最少空闲多久后可被清除
    min-evictable-time-millis: 30000
    #Druid用来测试连接是否可用的SQL语句,默认值每种数据库都不相同：
    validation-query: SELECT '1'
    #如果为true（默认true），当应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用。
    test-while-idle: true
    #如果为true（默认false），当应用向连接池申请连接时，连接池会判断这条连接是否是可用的。
    test-on-borrow: false



  redis:
    #超过时间
    timeout: 10000ms
    #地址
    host: 120.79.7.36
    #端口
    port: 6382
    #数据库
    database: 0
    password: rzkruizhukai123.
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 1024
        # 最大连接阻塞等待时间,默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
    #哨兵模式
    sentinel:
      #主节点名称
      master: mymaster
      #节点
      nodes: 120.79.7.36:26381,120.79.7.36:26382,120.79.7.36:26383
#文件大小 MB必须大写
#  maxFileSize 是单个文件大小
#  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  type-aliases-package: com.rzk.pojo
  mapper-locations: classpath:mapper/*.xml

#pagehelper分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 120.79.7.36:22122
    - 120.79.7.36:22122
rzk:
  url: http://120.79.7.36:88

minio:
  endpoint: http://124.221.132.14:9999 #Minio服务所在地址
  bucketName: rzk #存储桶名称
  accessKey: VLOOtQHn3r54UOOO #访问的key
  secretKey: K2CkERoaUrQ9fBa0ZiJwaOmvNkhzjSms #访问的秘钥

